---
title: "NHH-2"
author: "鄭至娟"
date: "8/23/2022"
output: html_document
---

#下載資料
install.packages("dplyr")
install.packages("readr")
install.packages("readxl")
install.packages("tidyr")
install.packages("magrittr")

#載入資料
library("dplyr")
library("readr")
library("readxl")
library("tidyr")
library("magrittr")

# dataset
Sales <- 
  read_excel("Geilo.xlsx",sheet ="Sales")

Sales[ Sales$cocoa > 0, ] #用逗點是因為後面可以篩選很多東西

Sales %>% filter( cocoa > 0 ) #只需寫一次

Sales %>% arrange(cocoa, orange,swix) %>% head(5) #前五大東西

# assigntment
Sales %>% arrange(cocoa,desc(orange),desc(swix)) %>% head(5)  #cocoa由小到大、orange由大到小、swix 由大到小
#Sales %>% arrange(cocoa,-orange,-swix) %>% head(5) #可以用-代替desc（因為是數值所以才可以用）

# 
Sales %>% select(cocoa,swix) %>% head(5)
Sales %>% mutate(items = cocoa + orange + swix, trans = trans) %>% head(5) # mutate新增新的變數items #trans 換名字
Sales %>% transmute(items = cocoa + orange + swix, trans = trans) %>% head(5) #transmute只保留上面的兩項
Sales %>% summarise(sum_cocoa = sum(cocoa)) #summarise可用於加總該數值

#assignment
#1. what many items were sold in total?
Sales %>%
  summarise(sum_items = sum(cocoa , orange , swix))

Sales %>% 
  mutate(items = cocoa + orange + swix) %>%
  summarise(sum_items = sum(items))  #也可以這樣寫
# what is min and max number of items purchase by consumers that bought at least one cocoa?
Sales %>% 
  mutate(items = cocoa + orange + swix) %>%
  filter(cocoa > 0) %>% #會直接過濾掉NA
  summarise(max_items = max(items),min_items = min(items))

#group
Sales %>% 
  group_by(customer) #灰色的指的是有幾種類型的人

Sales %>%
  group_by(customer)%>%
  summarise(sum.orange = sum (orange),no.trans = n()) #可以把某一群組的人他們加總起來
  
Sales %>%
  mutate(items = cocoa + orange + swix) %>% #建立新的欄位
  group_by(customer) %>% # 用顧客加總
  mutate(item_share = items/sum(items)) #新建立一個欄位（產品占有率）

Sales %>%
  mutate(items = cocoa + orange + swix) %>% #建立新的欄位
  group_by(customer) %>% # 用顧客加總
  mutate(item_share_customer = items/sum(items)) %>%
  ungroup() %>%
  mutaute(item_share = items/sum(items)) 
  
#
customer <- read_excel("Geilo.xlsx",sheet ="Customers") 

Sales %>% 
left_join(customer, by = "customer") #併表

Sales %>% 
  left_join(customer, by = "customer") %>% 
  group_by(hotel) %>% 
  summarise(sum_orange = sum(orange)) #併表，用hotel計算再進行加總每個買了多少orange

#assignment 想要找到沒有註冊的人
Sales %>% 
  left_join(customer, by = "customer") %>% 
  arrange(desc(customer)) %>%
  filter(is.na(hotel)) 
  
  
